<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="0" failures="2" finished="true" name="Test Run: 47" tests="2" total_time="Finished in: 1.58 secs."/>
<test location="Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py" status="fail" test="test_validate_view_category_items2" time="0.11">
<stdout><![CDATA[////////////////def get_categories_fooditems///////////////////////

]]></stdout>
<stderr><![CDATA[File "Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py", line 87
in test_validate_view_category_items2
    output = Validate.validate_view_category_items(restaurant_type,restaurant_name)
File "Z:\FA3\Project-PyFood\PyFood\validations\Validate.py", line 30
in validate_view_category_items
    raise InvalidCatItemsException
E   exceptions.CustomException2.InvalidCatItemsException: The category items is invalid]]></stderr>
</test>
<test location="Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py" status="fail" test="test_validate_item_present" time="0.05">
<stdout><![CDATA[def test_validate_item_present():
//////////////////def get_selected_food_items_present/////////////////////

restaurant_name
Kamar Hotel
]]></stdout>
<stderr><![CDATA[File "Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py", line 99
in test_validate_item_present
    output = Validate.validate_item_present(category_items,restaurant_name)
File "Z:\FA3\Project-PyFood\PyFood\validations\Validate.py", line 41
in validate_item_present
    raise Validate_item_present()
E   exceptions.CustomException2.Validate_item_present: The selected item is Not Present in Menu , Please Re-Enter Again]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="PyFood TestcasesModule3.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
