<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="0" failures="1" finished="true" name="Test Run: 21" tests="7" total_time="Finished in: 1.81 secs."/>
<test location="Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py" status="ok" test="test_validate_input_is_decimal" time="0.00">
<stdout/>
<stderr/>
</test>
<test location="Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py" status="ok" test="test_validate_input_is_decimal2" time="0.00">
<stdout><![CDATA[Please enter a Decimal Number!
]]></stdout>
<stderr/>
</test>
<test location="Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py" status="ok" test="test_validate_input_is_decimal3" time="0.00">
<stdout><![CDATA[Please enter a Decimal Number!
]]></stdout>
<stderr/>
</test>
<test location="Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py" status="ok" test="test_validate_item_available" time="0.10">
<stdout><![CDATA[len(category_items)
1
//////////////////def get_food_items_availability/////////////////////

Starters
list_of_item_available
['A ']
output
True
]]></stdout>
<stderr/>
</test>
<test location="Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py" status="ok" test="test_validate_item_available3" time="0.02">
<stdout><![CDATA[len(category_items)
2
//////////////////def get_food_items_availability/////////////////////

Starters
Chicken Tawa
list_of_item_available
[]
No Rows Returned for that selected items
[False]
]]></stdout>
<stderr/>
</test>
<test location="Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py" status="ok" test="test_validate_item_available4" time="0.04">
<stdout><![CDATA[len(category_items)
2
//////////////////def get_food_items_availability/////////////////////

Starters
ChickenDrama
list_of_item_available
[]
No Rows Returned for that selected items
]]></stdout>
<stderr/>
</test>
<test location="Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py" status="fail" test="test_validate_view_category_items" time="0.03">
<stdout><![CDATA[////////////////def get_categories_fooditems///////////////////////

]]></stdout>
<stderr><![CDATA[File "Z:\FA3\Project-PyFood\PyFood\testcases\TestcasesModule3.py", line 83
in test_validate_view_category_items
    output = Validate.validate_view_category_items(restaurant_type,restaurant_name)
File "Z:\FA3\Project-PyFood\PyFood\validations\Validate.py", line 32
in validate_view_category_items
    raise InvalidCatItemsException
E   exceptions.CustomException2.InvalidCatItemsException: The category items is invalid]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="PyFood TestcasesModule3.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
